---
sudo: false
language: c
cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
addons:
  apt:
    packages:
      - libgmp3-dev
matrix:
  include:

    - env: TARGET=x86_64-unkown-linux-gnu
      addons:
        apt:
          update: true
          sources:
            - hvr-ghc
          packages:
            - ghc-8.6.5
            - cabal-install-2.4

    - env: TARGET=x86_64-apple-darwin
      os: osx

before_install:
  - |
    if [ `uname` = "Darwin" ]
    then
      brew install cabal-install
      cabal new-update
    else
      export PATH=/opt/ghc/bin:$PATH
      cabal new-update
    fi
  - export PATH=$HOME/.cabal/bin:$PATH

script:
  - cabal new-build
  - |
    if [ `uname` = "Darwin" ]
    then
      export BINPATH="$(find dist-newstyle/ -name phash -perm 755 | tail -n1)"
    else
      export BINPATH="$(find dist-newstyle/ -name phash -executable | tail -n1)"
    fi
  - echo $BINPATH
  - mv $BINPATH phash-$TARGET
  - strip phash-$TARGET

deploy:
  api_key:
    secure: "Z2xSaCmx4ZQ0A7ygZitAw3S7NwvU99T8FTRlFhfRDngMcrlKE+p/XCiZRUZdPGhedVaWhy4t2fJWyPCMUq/VOtcjB7ZE2OazirMWAZmtqecSjKdqpvz7+mGK2Etvr//7RD9dxmqumOZmipYGsIOIwuYWAH7XuBEY2ymeNNlkkTAbKIBx2oitFYVA4UciSMcXAblvjgYrfAJlCbN/Pp2zbBt88vJjnxKeBNHqAC3gYwwTCpohYKXWK4iA5XexLSuoxLyZN6K1br5sh8JUNOPjtqNLcaU/ywNAOVbeYZZjMEGHDV1EUHecNlMpCFQ/JkJpBYjutwzmg6avbeE31HMnsuaNIcRJmzvguWbYXXB/Iqv9Xha2TLmGFWszo3Y+1VJcX6UB+rVCmgMRszXzGYFsTEBDaVAPXjPab298AEJ57XGXxwDwb3SEninTtfOA5mAKltN1jctCMUvAJkjW93MYXF/2fQHQq7dyDalQaZA1flq77ukUnUPGy0mUp/dF6TCwe7Bh1wOn6tKUc/R1UYA4hX2vX//xo69cWJ7w29m3GBifPcvSfo/Eg4oNiHXjbK65RG43+omPIbxr1zCIT2EzLiVDLQ27TCW88RVPFusQulP63aqpPz18hcUYudTzGcadwr/O5JYlpjqpu94lcg/cjHc3Mo1ywt4bWjWrduRFeXE="
  file: phash-$TARGET
  on:
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    - master
    - /\d+\.\d+\.\d+\.\d+.*$/
